
version: 0.5.{build}

image: Visual Studio 2017

branches:

  except:
  
    - gh-pages

skip_tags: true

install:

  - .paket\paket.bootstrapper.exe
  
  - .paket\paket.exe restore

cache:
  - packages -> paket.lock

build_script:
  
  - cmd: build build
      
test_script:
  
  - cmd: build test

artifacts:

  - path: build\nuget\*.nupkg

deploy:
  
  - provider: GitHub
    release: fortress-v$(appveyor_build_version)
    description: 'Unofficial Castle Windsor on dotnet core'
    auth_token:
      secure: sZD4+HypTqlQYLcBv+EkKIc0EWYGkeT4LUXmY0ALqyDQH6n++fBAQZTHaltI4SsM 
    artifact: build\nuget\*.nupkg       
    draft: false
    prerelease: true
    on:
      branch: master                 
    appveyor_repo_tag: true

  - provider: NuGet
    api_key:
      secure: GYMQ4rHqUYL5BcjMn2L9cs72K4YwEPfGRK9VWj1w6PswqbEWKrGUKICa064OUKRD
    skip_symbols: false
    artifact: build\nuget\*.nupkg 