
version: 0.5.{build}

image: Visual Studio 2017

branches:

  except:
  
    - gh-pages

skip_tags: true

install:

  - .paket\paket.bootstrapper.exe
  
  - .paket\paket.exe restore

cache:
  - packages -> paket.lock

build_script:
  
  - cmd: build
      
test_script:
  
  - cmd: build test