
version: 1.0.{build}

image: Visual Studio 2017

branches:

  except:
  
    - gh-pages

skip_tags: true

install:

  - .paket\paket.bootstrapper.exe
  
  - .paket\paket.exe restore

assembly_info:
  
  patch: false
  
  file: SolutionInfo.*
  
  assembly_version: "1.0.{build}"
  
  assembly_file_version: "{version}"
  
  assembly_informational_version: "{version}"

configuration: Release

cache:
  - packages -> paket.lock

build_script:
  
  - cmd: build.bat
      
test_script:
  
  - cmd: build test